[package]
name = "command_executor_server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
serialport = { version = "4.2.2" }
