name: Dev CI

on:
  push:
    branches:
      - '**' # Matches every branch.
      - '!master' # Excludes master.

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install Rust Toolchain
      uses: actions-rs/toolchain@v1.0.6
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Install Webpack Dependencies and Build Frontend
      run: cd client && npm i && npm run build-proto && npm run build-prod && cd ..
    - name: Build Backend
      run: |
        sudo apt-get update
        cd motor_server
        cargo fmt -- --check
        cargo clippy -- -D warnings
        cargo build
        cd ..
